version: '3.8'

services:
  web:
    # Construir usando el Dockerfile del directorio actual (.)
    build: .
    container_name: flask_login_backend
    
    # Mapeo de puertos: Puerto PC : Puerto Contenedor
    ports:
      - "5000:5000"
    
    # Volúmenes: Sincroniza tu carpeta actual con /app en el contenedor.
    volumes:
      - .:/app
    
    # Carga las variables de entorno desde el archivo .env
    env_file:
      - .env